### ISSUE TITLE
Java exception in thread "main" when running awscli

### ISSUE THREAD

**Issue by RaananF** [oktadev/okta-aws-cli-assume-role#400]
Followed the installation guide and when i'm trying to verify the installation or even run the basic awscli i get an exception

I get this error:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(URI.java:3164)
	at java.base/java.net.URI.<init>(URI.java:623)
	at java.base/java.net.URI.create(URI.java:904)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at com.okta.tools.saml.OktaAppClientImpl.launchApp(OktaAppClientImpl.java:40)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:59)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:45)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:132)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

Tried removing and reinstalling everything and nothing worked. Everything is the correct version.

**Comment by sethkong** [comment]
i am facing the same issue, does anyone figure out the solution?

**Comment by mraible** [comment]
If y'all do figure out a workaround, we might want to add it to the README. It's possible the JDK version matters.

**Comment by JD-LAVAUD** [comment]
check that you have a config file in ~/.okta and that it's properly named 'config.properties' , etc.. in case of file not found / badly named this error is thrown
